on:
  script:
    path: ./src/curseforge.js
    deduplicationKey: id
jobs:
  discord:
    name: send to discord
    runs-on: ubuntu-latest
    steps:
      - name: Actions for Discord
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with: 
          args: 'new ${{on.script.outputs.releaseType}} released: ${{on.script.outputs.fileName}}'