on:
  script:
    path: ./src/curseforge.js
    deduplicationKey: id
jobs:
  discord:
    name: send to discord
    runs-on: ubuntu-latest
    steps:
      - name: Actions for Discord
        uses: rjstone/discord-webhook-notify@v1
        with: 
          serverity: info
          color: '#ff00aa'
          description: New ${{ on.script.outputs.releaseType }} released.
          details: 'File: ${{ on.script.outputs.fileName }} \n Game version: ${{on.script.outputs.gameVersion}} \n Release date: ${{on.script.outputs.fileDate}}'
          username: Curseforge
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
