on:
  # script:
  #   path: ./src/curseforge.js
  #   deduplicationKey: id
  push:
    branches:
      - main
jobs:
  discord:
    name: send to discord
    runs-on: ubuntu-latest
    steps:
      - name: Actions for Discord
        uses: appleboy/discord-action@master
        with: 
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          # message: "new ${{on.script.outputs.releaseType}} released: ${{on.script.outputs.fileName}}"
          message: "new commit message"