on:
  rss:
    url: https://hnrss.org/newest?points=300&count=3
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.rss.outputs.title}}
          contentSnippet: ${{on.rss.outputs.contentSnippet}}
          link: ${{on.rss.outputs.link}}
        run: |
          echo title: $title
          echo contentSnippet: $contentSnippet
          echo link: $link
      - name: Test Custom
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          username: CustomUsername
          color: '#ff00aa'
          avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
          description: This is a custom description.
          details: 'Custom details: Somebody set up us the bomb.'
          footer: This is a footer.
          text: This is where text goes.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}